// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTmrfycLUeVyUV39Zv0eKDwGaqm5CK5vg',
    appId: '1:798745502255:web:8bd6ee42dbc56120c29cda',
    messagingSenderId: '798745502255',
    projectId: 'flutter-crud-42d34',
    authDomain: 'flutter-crud-42d34.firebaseapp.com',
    storageBucket: 'flutter-crud-42d34.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDllCKlQm72whHtyNvzmw5UecJ3648mIIA',
    appId: '1:798745502255:android:5bee9039fd860bc0c29cda',
    messagingSenderId: '798745502255',
    projectId: 'flutter-crud-42d34',
    storageBucket: 'flutter-crud-42d34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrPWUfd2lm15SrOgpap5DrER_6QNDQBws',
    appId: '1:798745502255:ios:b8571f9226d979afc29cda',
    messagingSenderId: '798745502255',
    projectId: 'flutter-crud-42d34',
    storageBucket: 'flutter-crud-42d34.appspot.com',
    iosBundleId: 'com.example.uiFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrPWUfd2lm15SrOgpap5DrER_6QNDQBws',
    appId: '1:798745502255:ios:b8571f9226d979afc29cda',
    messagingSenderId: '798745502255',
    projectId: 'flutter-crud-42d34',
    storageBucket: 'flutter-crud-42d34.appspot.com',
    iosBundleId: 'com.example.uiFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTmrfycLUeVyUV39Zv0eKDwGaqm5CK5vg',
    appId: '1:798745502255:web:b9a7cd8b3ccff768c29cda',
    messagingSenderId: '798745502255',
    projectId: 'flutter-crud-42d34',
    authDomain: 'flutter-crud-42d34.firebaseapp.com',
    storageBucket: 'flutter-crud-42d34.appspot.com',
  );
}
